name: HABiCenv
channels:
    - pytorch
dependencies:
    - cudatoolkit=11.3.1
    - numpy=1.26.3
    - pandas=1.3.4
    - pytorch=1.11.0
    - python=3.9.18
    - scikit-learn=1.3.0
    - torchvision=0.15.2
    - tqdm=4.65.0



